'use client'

import { useState } from 'react'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'

interface Props {
  valuationId: string
}

export function AINarrative({ valuationId }: Props) {
  const [narrative, setNarrative] = useState<string | null>(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState(false)

  const fetchNarrative = async () => {
    setLoading(true)
    setError(false)

    // Initial + 3 retries with exponential backoff (spec: 1s, 4s, 16s)
    const delays = [0, 1000, 4000, 16000]
    for (let attempt = 0; attempt < delays.length; attempt++) {
      if (attempt > 0) await new Promise(r => setTimeout(r, delays[attempt]))

      try {
        const res = await fetch('/api/ai-analysis', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ valuation_id: valuationId }),
        })

        if (res.ok) {
          const data = await res.json()
          setNarrative(data.narrative)
          setLoading(false)
          return
        }
      } catch {
        // Continue to next attempt
      }
    }

    setError(true)
    setLoading(false)
  }

  return (
    <Card className="bg-slate-900 border-slate-800">
      <CardHeader>
        <CardTitle className="text-white">AI-Powered Investment Analysis</CardTitle>
        <p className="text-sm text-slate-400">
          Generated by Claude — senior VC analyst perspective
        </p>
      </CardHeader>
      <CardContent>
        {!narrative && !loading && !error && (
          <div className="text-center py-4">
            <p className="text-sm text-slate-400 mb-3">
              Get AI-generated investment insights specific to your startup
            </p>
            <Button onClick={fetchNarrative} className="bg-amber-500 hover:bg-amber-600 text-black">
              Generate AI Analysis
            </Button>
          </div>
        )}

        {loading && (
          <div className="text-center py-4">
            <p className="text-sm text-slate-400 animate-pulse">
              Generating analysis... This takes 5-10 seconds.
            </p>
          </div>
        )}

        {error && (
          <div className="text-center py-4">
            <p className="text-sm text-slate-400 mb-2">
              AI analysis is currently unavailable. Please try again later.
            </p>
            <Button variant="outline" onClick={fetchNarrative} className="border-slate-700 text-slate-300">
              Retry
            </Button>
          </div>
        )}

        {narrative && (
          <div className="prose prose-sm prose-invert max-w-none whitespace-pre-wrap text-slate-300">
            {narrative}
          </div>
        )}
      </CardContent>
    </Card>
  )
}
